options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # build docker image
  - name: 'gcr.io/cloud-builders/docker' #image prebuild oleh google
    args: ['build', '-t', 'gcr.io/automated-axis-428810-n4/fastapi-app:latest', '.']

    # push image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/automated-axis-428810-n4/fastapi-app:latest']

  # deploy to cloud run
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args: ['run', 'deploy', 'fast-api-test', '--image', 'gcr.io/automated-axis-428810-n4/fastapi-app:latest','--region', 'us-central1', '--platform', 'managed', --allow-unauthenticated]
  
  # deploy to cloud GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: 
    - '-c'
    | 
    kubectl apply -f kubernetes/deployment.yaml
    kubectl apply -f kubernetes/service.yaml

images:
  - 'gcr.io/automated-axis-428810-n4/fastapi-app:latest'



